Robert Miller

I pledge my Honor that I Have abided by the Stevens Honor System

# Linear Regression Modification

In [56]:
#a) Import pandas and read df
#Start by imporating pandas and the data
import pandas as pd
df = pd.read_csv('Realestate.csv')

In [57]:
#Drop numbers? It will get in the way
df = df.drop(columns = "No")

In [58]:
#b) Standardize the
#.mean() returns the average for the cols, and .std will return the standard deviation
for col in df.columns:
  df[col] = (df[col] - df[col].mean()) / df[col].std()
#Store Y in an array
y = df['Y house price of unit area']
#then drop it from the features in dataframe
df = df.drop(columns = "Y house price of unit area")

In [59]:
#c)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
model = LinearRegression()
model.fit(df, y)

LinearRegression()

In [60]:
#predict values
y_hat = model.predict(df)
# print(y_hat)
#report the root mean square error value (RMSE)
sklearnRMSE = np.sqrt(mean_squared_error(y, y_hat))
print("RMSE: ", sklearnRMSE)

RMSE:  0.6454616841394373


In [61]:
#d) Numpy Linear Regression
#I copied and pasted this from the lecture's notebook code, as said in the homework document
class Linear_regression():

    def __init__(self, learning_rate, iterations):
        self.learning_rate = learning_rate
        self.iterations = iterations

    # Model Training Function
    def fit( self, X, Y):

        # Number of training example, Number of features
        self.m, self.n = X.shape

        # Weight initialization

        self.W = np.zeros( self.n)
        self.b = 0
        self.X = X
        self.Y = Y

        # Gradient Descent Learning
        for i in range(self.iterations):
            self.update_weights()
        return self

    # Function to update weights in Gradient Descent
    def update_weights(self):
        Y_pred = self.predict( self.X)

        # Gradient calculations
        dW = - (2 * (self.X.T).dot( self.Y - Y_pred)) / self.m
        db = - 2 * np.sum( self.Y - Y_pred) / self.m

        # Weight updates
        self.W = self.W - self.learning_rate * dW
        self.b = self.b - self.learning_rate * db

        return self
    # Hypthetical Function
    def predict( self, X):

        return X.dot( self.W) + self.b


In [62]:
model2 = Linear_regression(learning_rate = 0.01, iterations = 5000)
model2.fit(df, y)
h_hat = model2.predict(df)
print("Learning Rate = 0.001, Iteratinos  = 5000")
print("Mean Absolute Error: ", mean_absolute_error(y, h_hat))
print("Mean Squared Error: ", mean_squared_error(y, h_hat))
print("Root Mean Squared Error: ", np.sqrt(mean_squared_error(y, h_hat)))

Learning Rate = 0.001, Iteratinos  = 5000
Mean Absolute Error:  0.45057549717256046
Mean Squared Error:  0.41662078569211963
Root Mean Squared Error:  0.645461684139438


In [63]:
#e) Stochastic Gradient Descent in this version, so I made is Linear_regression2
#I copied and pasted this from the lecture's notebook code, as said in the homework document
class Linear_regression2():

    def __init__(self, learning_rate, iterations):
        self.learning_rate = learning_rate
        self.iterations = iterations

    # Model Training Function
    def fit( self, X, Y):

        # Number of training example, Number of features
        self.m, self.n = X.shape

        # Weight initialization

        self.W = np.zeros( self.n)
        self.b = 0
        self.X = X
        self.Y = Y

        # Stochastic Gradient Descent Learning
        for i in range(self.iterations):
            self.update_weights()
        return self

    # Function to update weights in Stochastic Gradient Descent
    def update_weights(self):

        #Shuffle X and Y
        shuffled_X = self.X.sample(frac = 1)
        shuffled_Y = self.Y.sample(frac = 1)
        for key, value in shuffled_X.iterrows():
          Y_pred = self.predict(shuffled_X.loc[key]) #the key is shuffled with X so y is shuffled in line
          # Stochastic Gradient calculations
          dW = - (2 * (shuffled_X.loc[key].T) * ( shuffled_Y.loc[key] - Y_pred)) / self.m
          db = - 2 * np.sum( self.Y - Y_pred) / self.m

          # Weight updates
          self.W = self.W - self.learning_rate * dW
          self.b = self.b - self.learning_rate * db

        return self
    # Hypthetical Function
    def predict( self, X):

        return X.dot( self.W) + self.b


In [64]:
model3 = Linear_regression2(learning_rate = 0.11, iterations = 50) #so few iterations since over 100 makes this take 5 mins on my computer
model3.fit(df, y)
h_hat = model3.predict(df)
print("Learning Rate = 0.11, Iteratinos  = 50")
print("Mean Absolute Error: ", mean_absolute_error(y, h_hat))
print("Mean Squared Error: ", mean_squared_error(y, h_hat))
print("Root Mean Squared Error: ", np.sqrt(mean_squared_error(y, h_hat)))

Learning Rate = 0.11, Iteratinos  = 50
Mean Absolute Error:  0.6393791684860177
Mean Squared Error:  0.6339925408537331
Root Mean Squared Error:  0.7962364855077498


# Bayesian Theroem

In [76]:
import pandas as pd
df = pd.read_csv('data.csv')
# print(df)

In [77]:
#b) calculate a probability of x and y
x_zero = 0
y_zero = 0
for key, row in df.iterrows():
  if row.X == 0 :
    x_zero += 1
  if row.Y == 0 :
    y_zero += 1
#df.shape[0] is the row count of the csv
#p(x=0)
px_zero =  x_zero / df.shape[0]
print("p(x = 0) = ",px_zero)
#p(x=1)
px_one = 1 - px_zero
print("p(x = 1) = ", px_one)
#p(y=0)
py_zero = y_zero / df.shape[0]
print("p(y = 0) = ", py_zero)
#p(y=1)
py_one = 1 - py_zero
print("p(y = 1) = ", py_one)

p(x = 0) =  0.5555555555555556
p(x = 1) =  0.4444444444444444
p(y = 0) =  0.5252525252525253
p(y = 1) =  0.4747474747474747


In [78]:
#c) Calculate the liklihoods of, P(A | B) = P(A && B) / P(B)
# p(x=0 | y = 0)
xzyz = df[(df['Y'] == 0) & (df['X'] == 0)].shape[0] / (df['Y'] == 0).sum()
print("p(x=0 | y = 0) = ", xzyz)
# # p(x = 1| y = 0)
xoyz = df[(df['Y'] == 0) & (df['X'] == 1)].shape[0] / (df['Y'] == 0).sum()
print("p(x=1 | y = 0) = ", xoyz)
# # p(x=0 | y = 1)
xzyo = df[(df['Y'] == 1) & (df['X'] == 0)].shape[0] / (df['Y'] == 1).sum()
print("p(x=0 | y = 1) = ", xzyo)
# # p(x = 1| y = 1)
xoyo = df[(df['Y'] == 1) & (df['X'] == 1)].shape[0] / (df['Y'] == 1).sum()
print("p(x=1 | y = 1) = ", xoyo)

p(x=0 | y = 0) =  0.5769230769230769
p(x=1 | y = 0) =  0.4230769230769231
p(x=0 | y = 1) =  0.5319148936170213
p(x=1 | y = 1) =  0.46808510638297873


In [79]:
#d) Calculate the posterior probabilies of, P(A | B) = P(B|A) * P(A) / P(B)
# p(y = 0 | x = 0)
yzxz = (xzyz * py_zero) / px_zero
print("p(y = 0 | x = 0) = ", yzxz)
# p(y = 0 | x = 1)
yzxo = (xoyz * py_zero) / px_one
print("p(y = 0 | x = 1) = ", yzxo)
# p(y = 1 | x = 0)
yoxz = (xzyo * py_one) / px_zero
print("p(y = 1 | x = 0) = ", yoxz)
# p(y = 1 | x = 1)
yoxo = (xoyo * py_one) / px_one
print("p(y = 1 | x = 1) = ", yoxo)

p(y = 0 | x = 0) =  0.5454545454545454
p(y = 0 | x = 1) =  0.5000000000000001
p(y = 1 | x = 0) =  0.4545454545454545
p(y = 1 | x = 1) =  0.5


# LDA

In [83]:
from sklearn import datasets
import numpy as np
X, y = datasets.make_blobs(n_samples = 100, n_features = 4, centers = 2, cluster_std = 1.5, random_state = 123)
y = np.array([-1 if i == 0 else 1 for i in y])

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X,y,test_size = 0.2, random_state = 42)

In [85]:
#Step 1 - calculate the mean separation, and between class matrix (Sb)
mean_vectors = []
m2 = np.mean(X_train[y_train == -1], axis = 0)
m1 = np.mean(X_train[y_train == 1], axis = 0)
mean_vectors.append(m1)
mean_vectors.append(m2)
print("Mean Vectors: ", mean_vectors)
mean_separation = m2 - m1
print("Mean Separation: ", mean_separation)
sB = np.outer(mean_separation , mean_separation.T)
print("Sb = ", sB)

Mean Vectors:  [array([ 3.86695443, -1.65152113,  9.54411923,  3.57230245]), array([ 4.13391297, -4.43739756, -5.17160943,  0.96271724])]
Mean Separation:  [  0.26695854  -2.78587643 -14.71572866  -2.60958521]
Sb =  [[ 7.12668604e-02 -7.43713495e-01 -3.92848939e+00 -6.96651049e-01]
 [-7.43713495e-01  7.76110748e+00  4.09962016e+01  7.26998193e+00]
 [-3.92848939e+00  4.09962016e+01  2.16552670e+02  3.84019479e+01]
 [-6.96651049e-01  7.26998193e+00  3.84019479e+01  6.80993497e+00]]


In [86]:
#Step 2 - compute Sw (within class scatter)
class_none = X_train[y_train == -1]
class_one = X_train[y_train == 1]

sW1 = np.dot((class_none - m1).T, (class_none - m1))
sW2 = np.dot((class_one - m2).T, (class_one - m2))
print("Sw1 = ", sW1)
print("Sw2 = ", sW2)
SW = sW1 + sW2
print("SW = ", SW)
SW_inverse = np.linalg.inv(SW)
print("SW^-1 = ", SW_inverse)

Sw1 =  [[ 109.63726451  -20.66474812 -177.17805303  -14.6574948 ]
 [ -20.66474812  445.13019314 1716.11056492  315.81648874]
 [-177.17805303 1716.11056492 9181.26536024 1628.5933453 ]
 [ -14.6574948   315.81648874 1628.5933453   387.54375197]]
Sw2 =  [[  85.17740249  -32.30373058 -153.52154243  -32.89242658]
 [ -32.30373058  379.78264102 1561.57969395  271.64703011]
 [-153.52154243 1561.57969395 8297.56706021 1446.10822877]
 [ -32.89242658  271.64703011 1446.10822877  304.98072565]]
SW =  [[  194.814667     -52.9684787   -330.69959545   -47.54992138]
 [  -52.9684787    824.91283416  3277.69025887   587.46351884]
 [ -330.69959545  3277.69025887 17478.83242044  3074.70157407]
 [  -47.54992138   587.46351884  3074.70157407   692.52447763]]
SW^-1 =  [[ 0.00533373 -0.00021089  0.00020352 -0.00035849]
 [-0.00021089  0.00478188 -0.00084293 -0.00032845]
 [ 0.00020352 -0.00084293  0.00041504 -0.0011137 ]
 [-0.00035849 -0.00032845 -0.0011137   0.00664266]]


In [87]:
#Step 3, solution can be found by Sw-1 * Sb
SW_inverse_SB = np.matmul(SW_inverse ,sB)
print("Inverse: ", SW_inverse_SB)
#calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(SW_inverse_SB)
eigenvalues = eigenvalues.real
eigenvectors =  eigenvectors.real
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: ", eigenvectors)
#Transform X_Train to project the eigenvetors
# X_transform = np.dot(X_train, eigenvectors)
#The best Eigenvalue for binary classification is 1.239569e-02, this one is the largest
#and is therefore better to use to distinguish between classes as it would a larger
#Separation between the classes
#The corresponding eigenvector, [-0.05874635, -0.14249608, -097591602, -0.15437502]

Inverse:  [[-1.28355038e-05  1.33946372e-04  7.07539806e-04  1.25470200e-04]
 [-3.11340008e-05  3.24902436e-04  1.71621973e-03  3.04342498e-04]
 [-2.13228118e-04  2.22516648e-03  1.17539119e-02  2.08435718e-03]
 [-3.37294335e-05  3.51987372e-04  1.85928945e-03  3.29713490e-04]]
Eigenvalues:  [-1.73472348e-18  1.23956923e-02 -1.08035799e-17 -2.33223047e-18]
Eigenvectors:  [[-0.99984555 -0.05874635 -0.01853645 -0.56283988]
 [-0.00250869 -0.14249608 -0.33888742  0.75761542]
 [-0.01718134 -0.97591602 -0.10200419 -0.09764458]
 [-0.00271783 -0.15437502  0.93509725 -0.31574624]]


In [88]:
from sklearn.metrics import accuracy_score
#Step 4, project chosen eigenvector onto the test data and predict
X_fit = np.dot(X_train, eigenvectors[:,1])
y_hat = np.where(X_fit <= 0, 1, -1) #this sets the predictions based on if the value in X_Fit is >= 0
accuracy = accuracy_score(y_train, y_hat)

print("Accuracy Score: ", accuracy)


Accuracy Score:  1.0


In [89]:
from sklearn.metrics import accuracy_score
#Step 5, project chosen eigenvector onto the train data and predict
X_fit = np.dot(X_test, eigenvectors[:,1])
y_hat = np.where(X_fit <= 0, 1, -1) #this sets the predictions based on if the value in X_Fit is >= 0
accuracy = accuracy_score(y_test, y_hat)

print("Accuracy Score: ", accuracy)


Accuracy Score:  1.0
